<?php
	DEFINE('WEBPATH','http://localhost/eresolute/');
	DEFINE('VIEW','views/');
	DEFINE('PAGE','pages/');
	DEFINE('INCLUDES','inc/');
	DEFINE('CTRL','controllers/');
	DEFINE('DB','eresolute');
	DEFINE('DBH','localhost');
	DEFINE('DBU','root');
	DEFINE('DBP','');
	DEFINE('SEG1','2');
	DEFINE('SEG2','3');
?>
